### ISSUE TITLE
Error: Cannot find module 'ngrok'

### ISSUE THREAD

**Issue by samirchian** [screener-io/screener-runner#41]
backtrace is :
```
Error: Cannot find module 'ngrok'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sasoon/source/BIM360IQ/client/node_modules/screener-runner/src/tunnel.js:1:75)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sasoon/source/BIM360IQ/client/node_modules/screener-runner/src/runner.js:4:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sasoon/source/BIM360IQ/client/node_modules/screener-runner/index.js:1:80)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sasoon/source/BIM360IQ/client/node_modules/screener-storybook/src/runner.js:2:14)
```
I am using npm 6.1.0

**Comment by loyalchow** [comment]
Hi @samirchian - we just did a clean install of `screener-runner` using npm 6.1.0 using the tunnel, and ran a test without issue.

- Were there any errors logged when initially running `npm install`? Can you re-run the install if the `ngrok` module was not installed properly?
- Which version of `screener-runner` and `screener-storybook` are you using?
- What do you get when running `npm ls ngrok`? Mine shows this:

```
npm-6.1.0@1.0.0
└─┬ screener-runner@0.10.0
  └── ngrok@2.2.24
```

**Comment by samirchian** [comment]
thanks!! I did run `npm i` again and it installed ngrok not sure why it was missing in first place.
